// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj5UwoakANfAxCUV7lS1cIG1jorhKAX2U',
    appId: '1:614964958750:web:b034f0fa2d3dd31094c00f',
    messagingSenderId: '614964958750',
    projectId: 'bookvista-final-version',
    authDomain: 'bookvista-final-version.firebaseapp.com',
    storageBucket: 'bookvista-final-version.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn8eUWmtHHp228aj-608wQ1M7RP62IFSo',
    appId: '1:614964958750:android:c7866465f32fbdbf94c00f',
    messagingSenderId: '614964958750',
    projectId: 'bookvista-final-version',
    storageBucket: 'bookvista-final-version.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY6UNZWVTyqQTtDQ4DdCjBjy8GU1E_c0c',
    appId: '1:614964958750:ios:7f1e57501f46d15c94c00f',
    messagingSenderId: '614964958750',
    projectId: 'bookvista-final-version',
    storageBucket: 'bookvista-final-version.firebasestorage.app',
    iosBundleId: 'com.example.bookvista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY6UNZWVTyqQTtDQ4DdCjBjy8GU1E_c0c',
    appId: '1:614964958750:ios:7f1e57501f46d15c94c00f',
    messagingSenderId: '614964958750',
    projectId: 'bookvista-final-version',
    storageBucket: 'bookvista-final-version.firebasestorage.app',
    iosBundleId: 'com.example.bookvista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj5UwoakANfAxCUV7lS1cIG1jorhKAX2U',
    appId: '1:614964958750:web:cf0501f9f4d7b3d094c00f',
    messagingSenderId: '614964958750',
    projectId: 'bookvista-final-version',
    authDomain: 'bookvista-final-version.firebaseapp.com',
    storageBucket: 'bookvista-final-version.firebasestorage.app',
  );
}
